Fix the card to expand seperatly
delegit-xyz/dashboard pull request #111
Opened 2024-09-09 12:52 UTC by wirednkod

closes #101

---

Submission checklist:

#### Layout

- [x] Fix cards to expand seperatly

![image](https://github.com/user-attachments/assets/7670b4e6-1946-466e-bddf-388f2d1d60fe)
![image](https://github.com/user-attachments/assets/1a193f1d-953f-4fd3-8c13-fa347d5eae11)

2024-09-09 14:29 UTC, Tbaut requested changes
see above

2024-09-09 21:31 UTC, wirednkod commented
> Can you please apply it to delegations too?

How many cards can exist there? In the first line there are max 3. In the "My delegations"?
I cannot create data due to the "ExhaustResources" bug

2024-09-09 21:41 UTC, Tbaut commented
For the exhaust resource, juste undelegate a couple tracks with pjs and delegate again with other convictions or others delegate. There can be many more cards, but I expect ppl to have 2 or 3 max. The vast majority will only have 1.

2024-09-09 21:47 UTC, wirednkod commented
![image](https://github.com/user-attachments/assets/21d6ad4e-38d0-4288-8904-c8affa2db95c)
![image](https://github.com/user-attachments/assets/011bf87f-890d-4547-8124-d3ce4b0d2a5b)

2024-09-09 22:15 UTC, Tbaut commented
it's not working on mobile any more :cry: 
![image](https://github.com/user-attachments/assets/96f1a9a7-4465-45d2-ac57-a298ebfd36df)

I'd like to keep this grid really, as this is what tailwind is supposed to allow you to do quickly. I'll check if we can have grid columns that are independants and still responsive, without having to use flex here.

2024-09-09 22:18 UTC, wirednkod commented
Ah.. my bad. I know why. Will fix in the morning

2024-09-10 15:14 UTC, Tbaut commented
This PR is now exploding, with new dependencies... and by adding new things.. well I'm adding new opinions :see_no_evil: 
Let's try to keep it focused, and discuss about things before you spend time on it.

As I wrote above:
> There can be many more cards, but I expect ppl to have 2 or 3 max. The vast majority will only have 1.

Meaning that the carousel is effectively useless for the vast majority! Can we remove it unless there are many (more than 3) delegates?

The spacing is off with the cards above. If not needed, the carousel should be invisible

![image](https://github.com/user-attachments/assets/70721de4-5d77-45a9-8fa3-2562d7798626)

2024-09-10 15:18 UTC, Tbaut reviewed
I feel bad pushing back on this.. but as nice as it may be for many delegates, it's useless for most cases, and just makes things complex, while we never discussed it :see_no_evil:

2024-09-10 18:17 UTC, Tbaut reviewed
That's very close to perfect, thank you so much!

2024-09-10 18:17 UTC, Tbaut commented on src/components/LocksCard.tsx
> +          <Card className="h-max border-2 p-2 px-4 md:col-span-1 md:col-start-1">
There's something wrong with this one, it always sits on top of the others :thinking: 
![image](https://github.com/user-attachments/assets/c5bde2cd-d863-4041-bb2d-c82c7abdcea0)

2024-09-10 18:45 UTC, wirednkod commented on src/components/LocksCard.tsx
> +          <Card className="h-max border-2 p-2 px-4 md:col-span-1 md:col-start-1">
Ah yeah.. I never get the unlockable tab so its hard to identify :) thnx for pointing it out

2024-09-10 19:30 UTC, Tbaut commented on src/components/LocksCard.tsx
> +          <Card className="h-max border-2 p-2 px-4 md:col-span-1 md:col-start-1">
Let's show it at all time, I don't see why this guy would be hidden when the others aren't :shrug:

2024-09-11 22:24 UTC, wirednkod commented on src/components/LocksCard.tsx
> +          <Card className="h-max border-2 p-2 px-4 md:col-span-1 md:col-start-1">
![image](https://github.com/user-attachments/assets/68111a64-425a-4ebf-8886-58c93c7d4305)

2024-09-12 11:46 UTC, Tbaut approved these changes
Super nice, looks great, just found a couple nits

2024-09-12 11:46 UTC, Tbaut commented on src/components/LocksCard.tsx
> +                            <Badge>{trackList[trackId]}</Badge> /{trackId}
Conflict went wrong here, it should be
```suggestion
                            <TrackDisplay trackId={trackId} />
```

2024-09-12 11:46 UTC, Tbaut commented on src/components/LocksCard.tsx
> +  const { api, assetInfo, trackList } = useNetwork()
with TrackDisplay there's no need from the list any more
```suggestion
  const { api, assetInfo } = useNetwork()
```

2024-09-12 11:46 UTC, Tbaut commented on src/components/LocksCard.tsx
> +                    Funds unlock after a certain time. These locks result either
I'd like to keep the same wording as the card, and if the card title is wrong, then let's change it. But the fact that users need to do something to get things unlocked makes me think "unlock" is not right. I agree unlockable is not great though..
```suggestion
                    Funds unlockable after a certain time. These locks result either
```

2024-09-12 13:49 UTC, merged