Add people parachain
delegit-xyz/dashboard pull request #124
Opened 2024-09-10 22:06 UTC by wirednkod

closes #123 

---

Submission checklist:

#### Functionality
- [x] Connect the people parachain based on the relay chain that is currently connected

#### Layout

- [ ] Add information on the Delegators card

2024-09-23 17:56 UTC, wirednkod commented
![Screenshot 2024-09-23 at 20 53 35](https://github.com/user-attachments/assets/3aeb4a31-9377-4efb-8b6d-df7ca45a6bce)
![Screenshot 2024-09-23 at 20 55 24](https://github.com/user-attachments/assets/1c34eabf-f0fb-4b9f-a812-517f34f1a049)
![Screenshot 2024-09-23 at 20 55 46](https://github.com/user-attachments/assets/61977871-1130-4ca8-a399-08f2dc6fcc6a)

2024-09-23 21:09 UTC, Tbaut reviewed
Nice, I didn't play with it yet and just went through the code.
I see a lot of `useEffect` with the `retrieveidentity` where it could have been done probably nicely in a custom `useidentity(address)` hook, that returns the `identity`.

I see you're not fetching the judgement yet. it can be added later, but I would show no checkmark then for the mean time.

2024-09-23 21:09 UTC, Tbaut commented on src/lib/utils.ts
> +  if (!rawIdentity) return rawIdentity
not sure I get this line, shouldn't it be just a `return` with undefined?

2024-09-23 21:09 UTC, Tbaut commented on src/lib/utils.ts
> +  } = rawIdentity[0]
Just a suggestion to make it easier to read.
```suggestion
  const { display, email, legal, matrix, twitter, web } = rawIdentity[0].info
```

2024-09-23 21:09 UTC, Tbaut commented on src/pages/Delegate/index.tsx
> +  }, [address, peopleApi])
This is re-doing what is done above. Also I don't think it's needed to pass this as a prop, it should all be done in `DelegateCard`

2024-09-23 21:09 UTC, Tbaut commented on src/pages/Delegate/index.tsx
> +  }, [address, delegate, getDelegateByAddress])
this looks like it's not related to this PR :thinking: is this a conflict resolution gone wrong?

2024-09-24 08:51 UTC, wirednkod commented on src/pages/Delegate/index.tsx
> +  }, [address, delegate, getDelegateByAddress])
Seems like it comes from your PR - not really sure 🤔 
![image](https://github.com/user-attachments/assets/6e3acc22-480c-4120-8081-ed3bbb19f875)

2024-09-24 15:18 UTC, Tbaut commented on src/pages/Delegate/index.tsx
> +  }, [address, delegate, getDelegateByAddress])
if it's not your code, and we're not sure, then please remove :shrug: 
it's already used above, see `foundDelegate`

There should be no change in this file.

2024-09-24 15:32 UTC, wirednkod commented on src/hooks/useIdentity.tsx
> +    retrieveIdentity()
Sorry missed that comment

2024-09-24 15:33 UTC, wirednkod commented on src/lib/utils.ts
> +export const getPeopleChainInformation = (
Hard no. It works fine and we can randomly select a wss. It works fine and we have multiple selections in case one is faulty. I want to do the same with the other as well (since at the moment we only pick the 1st of the list)

2024-09-24 15:48 UTC, Tbaut commented on src/lib/utils.ts
> +export const getPeopleChainInformation = (
If you want me to accept this, we'll have to add some kind of fail over. If the connection doesn't work withing a couple sec, to fail over to another one. We had issues originally bc we had a random list of nodes, some of which were not working. refrsh and it works is a super bad UX. So either we go with the one that works and has always worked so far, or we go with random, but with proper checks and rotation :shrug:

2024-09-25 09:29 UTC, Tbaut requested changes

2024-09-25 09:29 UTC, Tbaut commented on src/contexts/AccountsContext.tsx
> +
This is not needed.

2024-09-25 09:29 UTC, Tbaut commented on src/contexts/AccountsContext.tsx
> +        ({ address }: AccountAddressType) => address === localStorageAccount,
`accounts` is of type `PolkadotAccount[]` so the type is inferred. You don't need to declare anything.
```suggestion
        ({ address }) => address === localStorageAccount,
```

2024-09-25 09:29 UTC, Tbaut commented on src/assets/peopleNetworks.json
This file is not needed any more is it? I'd put the network wss in the `networks.json` file, under the other networks. But I can do this in another PR.

2024-09-25 09:29 UTC, Tbaut commented on src/contexts/NetworkContext.tsx
> +    const descriptorPeople = descriptorPeopleName[peopleNetwork!]
No need of an assertion here, it's set in any case.
```suggestion
    const descriptorPeople = descriptorPeopleName[peopleNetwork]
```

2024-09-25 09:29 UTC, Tbaut commented on src/lib/types.ts
> +
May not be needed if removed.

2024-09-25 09:29 UTC, Tbaut commented on src/lib/utils.ts
> +export const getPeopleChainInformation = (
not used any more

2024-09-25 09:29 UTC, Tbaut commented on src/lib/utils.ts
> +const randomFromInterval = (min: number, max: number) =>
not used any more

2024-09-25 09:29 UTC, Tbaut commented on src/pages/Delegate/index.tsx
> +  if (!delegate || !api) return <div>No delegate found</div>
please remove, unless you're fixing a known bug, there is no need for this, this is handled below.

2024-09-25 13:56 UTC, Tbaut approved these changes

2024-09-25 13:56 UTC, merged

2024-09-25 14:00 UTC, Tbaut commented on src/contexts/AccountsContext.tsx
> +
I'll fix this in a subsequent PR