Create links and make them beautiful
delegit-xyz/dashboard pull request #146
Opened 2024-09-16 16:26 UTC by wirednkod

closes #139 

---

Submission checklist:

#### Layout

- [x] Create link icon next to each title

2024-09-16 21:29 UTC, Tbaut requested changes
That's a really cool functionality! I've a couple suggestions here and there

2024-09-16 21:29 UTC, Tbaut commented on src/components/DelegateCard.tsx
> +
`copied` and `setCopied` aren't used.
`copyLink` can be set directly in a `useMemo`
Let's go with `useCallbacks` for the others, to make sure all const are up to date.
```suggestion
  const { network } = useNetwork()
  const navigate = useNavigate()
  const { search } = useLocation()
  const copyLink = useMemo(() => `${window.location.host}/${network}/${sanitizeString(name)}`, [name, network])
  const shouldHideLongDescription =
    !longDescription || longDescription === shortDescription

  const onDelegate = useCallback(() => {
    navigate(`/delegate/${address}${search}`)
  },[address, navigate, search])

  const onCopy = useCallback(() => {
    navigator.clipboard.writeText(copyLink)
    toast.success('Copied to clipboard', {
      duration: 1000,
    })
  }, [copyLink])
```

2024-09-16 21:29 UTC, Tbaut commented on src/pages/Delegate/index.tsx
> +    if (isValidAddress(address!)) {
Can we do an early return rather than casting, we're not sure that the address will be defined
```suggestion
  if(!address) return

    if (isValidAddress(address)) {
```

2024-09-16 21:29 UTC, Tbaut commented on src/pages/Delegate/index.tsx
> +  const [newAddress, setNewAddress] = useState<string>()
I'm surprised this passes compilation since it's undefined.
Can we call this `validAddress`? since it's not really new.
```suggestion
  const [newAddress, setNewAddress] = useState<string>('')
```

2024-09-16 21:29 UTC, Tbaut commented on src/pages/Delegate/index.tsx
> +      const delegate = getDelegateByName(address!)
```suggestion
      const delegate = getDelegateByName(address)
```

2024-09-16 21:29 UTC, Tbaut commented on src/pages/Delegate/index.tsx
> +      delegate?.address && setNewAddress(delegate?.address)
```suggestion
      !!delegate && setNewAddress(address)
```

2024-09-16 21:29 UTC, Tbaut commented on src/lib/utils.ts
> +    // replace all strange characters to underscores
```suggestion
    // replace all strange characters with underscores
```

2024-09-16 21:29 UTC, Tbaut commented on src/Content.tsx
> +    element: <Delegate />,
since we're doing a redirect, what do you think about having a dedicated component for this.
with a loader, and at the end we do a redirect to `<Delegate />`? Bc right now, there's quite a lot of logic in the Delegate component just for this, and it's getting bloated.

We can also do it in a separate refactoring PR.

2024-09-16 21:37 UTC, wirednkod commented on src/pages/Delegate/index.tsx
> +  const [newAddress, setNewAddress] = useState<string>()
useState does not care at init if its undefined (if it is filled on first `set...` it wont complain) - but sure

2024-09-16 21:38 UTC, wirednkod commented on src/pages/Delegate/index.tsx
> +      delegate?.address && setNewAddress(delegate?.address)
This is wrong. You want to add here the address from the delegate that will be retrieved and not the address that comes from the url

2024-09-16 21:38 UTC, wirednkod commented on src/Content.tsx
> +    element: <Delegate />,
I mean  sure.. but it does not really matter. We could refactor later on

2024-09-16 22:22 UTC, Tbaut commented on src/pages/Delegate/index.tsx
> +      delegate?.address && setNewAddress(delegate?.address)
there's something wrong here `getDelegateByName` and we pass an address?

2024-09-16 22:23 UTC, Tbaut commented on src/pages/Delegate/index.tsx
> +      delegate?.address && setNewAddress(delegate?.address)
> You want to add here the address from the delegate that will be retrieved and not the address that comes from the url

But isn't it the same? we check whether the delegate exist, by address (weird that we call byName here actually)

2024-09-17 08:53 UTC, Tbaut commented on src/pages/Delegate/index.tsx
> +  const [newAddress, setNewAddress] = useState<string>()
it's not about if it cares or not, it's about the type you've set. if it's `string` but you set it to undefined, then it'll complain that string can't be undefined.

2024-09-17 09:47 UTC, Tbaut commented
I'm not happy with the amount of weird logic here, so I pushed a PR to have it all in a component that's made specifically for this. Please let me know what you think https://github.com/delegit-xyz/dashboard/pull/152 You can merge, and then we merge this one.

2024-09-17 18:17 UTC, wirednkod commented
> I'm not happy with the amount of weird logic here, so I pushed a PR to have it all in a component that's made specifically for this. Please let me know what you think #152 You can merge, and then we merge this one.

Wont try to fight this. We could have done it after the merge but since you did it already feel free to merge as you see fit

2024-09-17 20:57 UTC, Tbaut commented on src/pages/Delegate/index.tsx
> +      delegate?.address && setNewAddress(delegate?.address)
You will not be able to convince me that `getDelegateByName(address)` is fine :) The name, the logic, something is off, and if I read this in a couple months from now, I'll have forgotten about the context. In any case, I've refactored this in #152 and we can discuss this there

2024-09-18 07:32 UTC, wirednkod commented
After Merging #152 this stopped working. Will have to fix that

2024-09-18 10:29 UTC, Tbaut commented
I can check it no worries, it worked in my tests, on my branch. Some small things went through in between

2024-09-18 12:04 UTC, wirednkod commented
> I can check it no worries, it worked in my tests, on my branch. Some small things went through in between

Dont worry. I look at it

2024-09-18 12:08 UTC, wirednkod commented
Works fine. Lets merge this :)

2024-09-18 14:24 UTC, Tbaut commented
There's something not working well with the way we fetch delegate. Maybe with the JSON. I'm investigating

2024-09-18 15:44 UTC, Tbaut commented
Looks ok now, I've been testing heavily, please do as well if you can.

2024-09-19 09:15 UTC, wirednkod commented on src/components/RedirectByName.tsx
> +  }
If network is not supported we should fall back to the default one

2024-09-19 09:15 UTC, wirednkod commented on src/components/RedirectByName.tsx
> +      setIsDelegateMissing(true)
we should fall back to the default if its not supported - not throw the error message

2024-09-19 09:15 UTC, wirednkod commented on src/components/RedirectByName.tsx
> +      setIsDelegateMissing(true)
we should fall back to the default if its not supported - not throw the error message

2024-09-19 09:15 UTC, wirednkod commented on src/contexts/DelegatesContext.tsx
> +      .catch(console.error)
should we throw a popup error here?

2024-09-19 09:20 UTC, Tbaut commented on src/components/RedirectByName.tsx
> +  }
I disagree, ppl may end up delegating on a network they didn't expect. Hard no.

2024-09-19 09:20 UTC, Tbaut commented on src/components/RedirectByName.tsx
> +      setIsDelegateMissing(true)
again, hard no.

2024-09-19 09:24 UTC, Tbaut commented on src/contexts/DelegatesContext.tsx
> +      .catch(console.error)
There was no error handling before, and I doubt there'll ever be issues with a github hosted static content. Should there be, we'll be able to see in the console now at least, but I wouldn't bother much.

2024-09-19 09:26 UTC, Tbaut commented on src/components/RedirectByName.tsx
> +      setIsDelegateMissing(true)
see above, I strongly disagree.

2024-09-19 10:40 UTC, Tbaut approved these changes
:rocket:

2024-09-19 10:40 UTC, merged