Fix some slowness
delegit-xyz/dashboard pull request #180
Opened 2024-10-05 15:34 UTC by Tbaut

closes #151

2024-10-05 23:18 UTC, Tbaut commented
The main issue was
- rendering of the modal even when not needed
- many complex functions re-rendering, the heaviest was `isExhaustedRessources`

If you type in the input now, it's instant. Before it took a sec for the text to appear.

2024-10-07 07:18 UTC, wirednkod requested changes

2024-10-07 07:18 UTC, wirednkod commented on src/header.tsx
> +import React, { useEffect, useState } from 'react'
lets keep it simple:
```suggestion
import { Fragment, useEffect, useState } from 'react'
```

2024-10-07 07:18 UTC, wirednkod commented on src/header.tsx
> +                    <React.Fragment key={account.address}>
```suggestion
                    <Fragment key={account.address}>
```

2024-10-07 07:18 UTC, wirednkod commented on src/header.tsx
> +                    </React.Fragment>
```suggestion
                    </Fragment>
```

2024-10-07 07:18 UTC, wirednkod commented on src/hooks/useTestTx.tsx
> +  const aliceKeyPair = useMemo(() => derive('//Alice'), [derive])
Not sure I understand this... derive (line 14) already uses `useMemo`. Why to reuse it?

2024-10-07 07:18 UTC, wirednkod commented on src/pages/Delegate/index.tsx
> +    }, [convictionNo, getConvictionLockTimeDisplay])
```suggestion
    useMemo(() => (
      getConvictionLockTimeDisplay(convictionNo) ||
      getConvictionLockTimeDisplay(convictionNo)
    ), [convictionNo, getConvictionLockTimeDisplay])
```

2024-10-07 07:18 UTC, wirednkod commented on src/pages/Delegate/index.tsx
> +      console.log('e.target.value', e.target.value)
is this needed?

2024-10-07 07:18 UTC, wirednkod commented on src/pages/Delegate/index.tsx
> +      console.log('date2 - date1', diff)
is this needed?

2024-10-07 08:37 UTC, Tbaut commented on src/hooks/useTestTx.tsx
> +  const aliceKeyPair = useMemo(() => derive('//Alice'), [derive])
Because we don't need to derive every single render if `derive` doesn't change. So thie `aliceKeyPair` will be derived once for all. Also I just memoize / useCallback everything at this point. Spending an hour to find the one function that makes everything slow is more time consuming than bluntly memoizing every single const IMHO. I used to do this in all my apps, chose not to be annoying for Delegit, and it bit us all the same. The experience of using the delegate page just got much much better thanks to this.

2024-10-07 08:37 UTC, Tbaut commented on src/pages/Delegate/index.tsx
> +      console.log('e.target.value', e.target.value)
absolutely not. Thanks

2024-10-07 08:38 UTC, Tbaut commented on src/pages/Delegate/index.tsx
> +      console.log('date2 - date1', diff)
absolutely not. Thanks

2024-10-07 08:43 UTC, Tbaut commented
Thanks for the review, and sorry for the 1000 oversights of logs etc :sweat_smile:

2024-10-07 08:44 UTC, wirednkod approved these changes

2024-10-07 08:44 UTC, merged