2 tx flow, first remove votes and undelegate then delegate
delegit-xyz/dashboard pull request #186
Opened 2024-10-10 12:54 UTC by Tbaut

closes #185 
closes #167 

![image](https://github.com/user-attachments/assets/caf126d6-62a1-49c0-a0a7-610c269218f7)

---

Submission checklist:

#### Layout

- [x] Change inspected in the mobile web ui
- [x] Change inspected in dark mode

2024-10-10 16:03 UTC, wirednkod requested changes

2024-10-10 16:03 UTC, wirednkod commented on src/components/LocksCard.tsx
> +          {/* <Card className="h-max border-2 p-2 px-4">
Please remove commented out code

2024-10-10 16:03 UTC, wirednkod commented on src/components/LocksCard.tsx
> +          </Card> */}
Please remove commented out code

2024-10-10 16:03 UTC, wirednkod commented on src/pages/Delegate/MultiTransactionDialog.tsx
> +                'The delegation process is in 2 parts. First, please sign a transaction to remove previous votes or delegations.'}
```suggestion
                'Please sign a transaction to clear any previous votes or delegations before proceeding with the delegation process.'}
```

2024-10-10 16:23 UTC, Tbaut commented on src/components/Alert.tsx
> +  message: string | React.ReactNode
Nah! this is pretty common and doesn't change anything in the code below. Having 2 variables makes it uglier, and doesn't change anything! For instance that's what we have in the `ContentReveal` and what many common libraries have too!

2024-10-10 16:23 UTC, Tbaut commented on src/components/LocksCard.tsx
> +          {/* <Card className="h-max border-2 p-2 px-4">
oh, forgot about it thx

2024-10-10 16:29 UTC, Tbaut commented on src/pages/Delegate/MultiTransactionDialog.tsx
> +                'The delegation process is in 2 parts. First, please sign a transaction to remove previous votes or delegations.'}
I find this long phrase that we had actually pretty bad, nobody reads such long things, it needs to be more actionable IMHO. What do you think about:
```
There will be 2 transactions:
1. Clear previous votes & delegations
2. Delegate
```

2024-10-10 16:43 UTC, Tbaut commented on src/pages/Delegate/MultiTransactionDialog.tsx
> +                'The delegation process is in 2 parts. First, please sign a transaction to remove previous votes or delegations.'}
I went for something straight forward. No need to "Please" and what not, they are asking for it, not delegit!
- First, let's clear previous votes or delegations.
- Now, we are ready to delegate.

WDYT?

2024-10-12 11:16 UTC, Tbaut commented
ping @wirednkod for another review please :pray:

2024-10-14 06:27 UTC, wirednkod commented on src/pages/Delegate/MultiTransactionDialog.tsx
> +                'The delegation process is in 2 parts. First, please sign a transaction to remove previous votes or delegations.'}
Sounds better.

2024-10-14 06:28 UTC, wirednkod approved these changes

2024-10-14 06:28 UTC, merged