deactivate direct to delegation page if account is not connected or a…
delegit-xyz/dashboard pull request #48
Opened 2024-08-25 16:35 UTC by wirednkod

…pi is not ready

Fixes #47 
Fixes #52

2024-08-25 17:19 UTC, wirednkod commented
Fixed by adding lovely Alerts:

![image](https://github.com/user-attachments/assets/5655a448-a797-412f-92b7-978bbf52b80a)

2024-08-25 17:23 UTC, Tbaut reviewed
Nice! I left small nits

2024-08-25 17:23 UTC, Tbaut commented on src/consts.ts
> +      'The delegation amount cannot be 0. Please add a DOT amount for delegation.',
This could also be KSM
```suggestion
      'Invalid amount. Please type an amount to delegate.',
```

2024-08-25 17:23 UTC, Tbaut commented on src/pages/Delegate/index.tsx
> +        disabled={amount === 0 || !api || !selectedAccount}
This is still very week and I bet things break if we put the wrong comma, or some string in that field, But anyway, trying to tackle more cases.

```suggestion
      {amount <= 0 && (
        <AlertNote
          title={msgs.zeroAmount.title}
          message={msgs.zeroAmount.message}
        />
      )}
      <Button
        onClick={onSign}
        disabled={amount <= 0 || !api || !selectedAccount}
```

2024-08-25 20:59 UTC, wirednkod commented on src/pages/Delegate/index.tsx
> +        disabled={amount === 0 || !api || !selectedAccount}
I have fixed that, by ensuring that commas are correctly replaced and all amounts are correctly fixed based on the decimals of the chain

2024-08-26 10:53 UTC, wirednkod commented on src/contexts/NetworkContext.tsx
> +    symbol: 'DOT',
Actually the client returns the results needed, meaning that the `await client.getChainSpecData()` returns:
```json
{
	genesisHash: "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3"
	name: "Polkadot"
	properties: {
		ss58Format: 0
		tokenDecimals: 10
		tokenSymbol:  "DOT"
	}
}
```
We still need the JSON you propose, but we can receive the information straight from the chain upon connection which makes our life easier

2024-08-26 10:54 UTC, wirednkod commented on src/pages/Delegate/index.tsx
> +    const res = evalUnits(e.target.value, decimals)
Good point.. Will fix <3

2024-08-27 17:15 UTC, Tbaut requested changes
Cool thanks a lot. Can we keep only the Kusama and Polkadot values of the JSON? Otherwise it's a lot of data that users need to download for no good reason, since we'll probably never use 98% of the networks in the JSON.

I left some nits here and there, looks great otherwise, thank you so much

2024-08-27 17:15 UTC, Tbaut commented on src/lib/constants.tsx
> +const PolkadotUrl = 'https://delegit-xyz.github.io/dashboard'
This looks weird, is that a mistake?

2024-08-27 17:15 UTC, Tbaut commented on src/contexts/NetworkContext.tsx
> +          cl = createClient(getWsProvider('wss://rpc.ibp.network/polkadot'))
I guess we should get this URL from the `supportedNetworksChainIds.kusama`?

2024-08-27 17:15 UTC, Tbaut commented on src/lib/utils.ts
> +  const randomWs = Math.floor(Math.random() * ws.length)
let's get the first to start with. We can, if we want let user choose eventually, but I wouldn't randomise. Some are arguably much better than others.

2024-08-27 17:15 UTC, Tbaut commented on src/pages/Delegate/index.tsx
> +    // eslint-disable-next-line prefer-const
can we fix this eslint?

2024-08-27 17:15 UTC, Tbaut commented on src/pages/Delegate/index.tsx
> +      setAmountError(sanitizedValue)
does "sanitizedValue" make sense here? I gave this name while reviewing, but as I said, I've no idea what that value is. it sounds like it's an error?

2024-08-28 06:59 UTC, wirednkod commented on src/lib/constants.tsx
> +const PolkadotUrl = 'https://delegit-xyz.github.io/dashboard'
Will Fix. This is in case we want to use the url as a text/url etc etc - instead of typing it - we can always use this constant

2024-08-28 07:00 UTC, wirednkod commented on src/contexts/NetworkContext.tsx
> +          cl = createClient(getWsProvider('wss://rpc.ibp.network/polkadot'))
this is a mistake. it should be replaced with wsProv - which actually is a random wss from the Novasama Jsons

2024-08-28 12:44 UTC, Tbaut approved these changes
Awesome, thank you so much. I just found a stray comment, I'll commit the suggestion and merge :)

2024-08-28 12:44 UTC, Tbaut commented on src/contexts/DelegateesContext.tsx
> +  // const [list, setList] = useState<Delegatee[]>()
stray comment
```suggestion
```

2024-08-28 12:48 UTC, merged

2024-08-28 12:52 UTC, Tbaut commented on src/lib/utils.ts
> +  const randomWs = Math.floor(Math.random() * ws.length)
all right, I'm not a fan of such uncertainty, as in, if ppl come and tell us "it doesn't work", and it's an rpc issue, we won't know which one. Also Refreshing to fix an issue is not a great experience, and we may not know for a while that ppl have issues, and the experience won't be great. I'd prefer to have some logic to go to the next in case one errors out, at least it's seamless.

2024-08-28 12:52 UTC, wirednkod commented on src/lib/utils.ts
> +    nw === 'polkadot'
I mean ... we decided to keep "only polkadot and kusama" - thats the reasoning behind that "if".
I assume that anyone who will add a new network - will test it first :D :D

2024-08-28 12:54 UTC, Tbaut commented on src/lib/utils.ts
> +    nw === 'polkadot'
Unless it adds a lot of overhead, we should just keep it in mind IMHO and avoid ternary if possible