Simplify adding network
delegit-xyz/dashboard pull request #59
Opened 2024-08-29 16:57 UTC by Tbaut

I need more network to test.
Westend and Fast Westend will be visible only in dev in the dropdown

I kept an `if` when we're asking for light client, because the dynamic import needs to have a deterministic name. Otherwise we'll load the descriptor somewhat dynamically.

If we want to add a network now, we can add it to the `networks.json` and follow the TS errors, more or less everything is in the network context beside the menu (in `header.tsx`).

2024-08-29 21:54 UTC, wirednkod requested changes

2024-08-29 21:54 UTC, wirednkod commented on src/contexts/NetworkContext.tsx
> +      client = createClient(getSmProvider(relayChain as unknown))
Smoldot can be imported from polkadot-api as well so you can add at the top:
```ts
import type { Chain } from 'polkadot-api/smoldot'
```
and then:
```suggestion
      client = createClient(getSmProvider(relayChain as Chain))
```

2024-08-29 21:54 UTC, wirednkod commented on src/header.tsx
>  ]
```suggestion
type NetworkListType =  { name: SupportedNetworkNames; display: string }

const networkList: NetworkListType[] = [
  { name: 'polkadot', display: 'Polkadot' },
  { name: 'polkadot-lc', display: 'Polkadot Light Client' },
  { name: 'kusama', display: 'Kusama' },
  { name: 'kusama-lc', display: 'Kusama Light Client' },
]

(import.meta.env.DEV)  &&  networkList.push(
	{ name: 'westend', display: 'Westend' },
        { name: 'fast-westend', display: 'Fast Westend' }
        )
```

2024-08-29 21:54 UTC, wirednkod commented on src/header.tsx
> +
Better to add this outside the  component to reduce render time and actions (see above)

```suggestion
```

2024-08-29 21:54 UTC, wirednkod commented on src/header.tsx
> +              {networkList.map(({ name, display }) => (
```suggestion
              {networkList.map(({ name, display }: NetworkListType) => (
```

2024-08-30 08:27 UTC, Tbaut commented on src/contexts/NetworkContext.tsx
> +      client = createClient(getSmProvider(relayChain as unknown))
oh nice, somehow my IDE didn't see it

2024-08-30 08:40 UTC, Tbaut commented on src/header.tsx
> +              {networkList.map(({ name, display }) => (
it's inferred now, gave a name to this type.

2024-08-30 09:23 UTC, merged